/**
 * Display-only transforms. The raw values survive untouched in "Copy event
 * details (JSON)", because the scrapers' output is the record of what the
 * source actually said and this file is only about what a person should read.
 */

/** Tokens that must keep their capitals when a title is recased. */
const ACRONYMS = new Set([
  'AI', 'UX', 'UI', 'API', 'STEM', 'DC', 'MD', 'VA', 'USA', 'NASA', 'BWI', 'UMBC',
  'JHU', 'MICA', 'NAACP', 'LGBTQ', 'IT', 'HR', 'CEO', 'VC', 'AR', 'VR', '3D',
]);

/** Small words that stay lowercase inside a title, but never lead it. */
const MINOR = new Set([
  'a', 'an', 'and', 'as', 'at', 'but', 'by', 'for', 'in', 'nor', 'of', 'on', 'or',
  'the', 'to', 'up', 'via', 'vs', 'with',
]);

const LETTER = /\p{L}/u;
const UPPER = /\p{Lu}/u;

function isAllCapsWord(token: string): boolean {
  const letters = [...token].filter((c) => LETTER.test(c));
  if (letters.length < 4) return false;
  return letters.every((c) => UPPER.test(c));
}

/** Recase one token, preserving acronyms and anything containing a digit. */
function recaseToken(token: string, index: number): string {
  const bare = token.replace(/[^\p{L}\p{N}]/gu, '');
  if (bare === '') return token;
  if (/\d/.test(token)) return token;
  if (ACRONYMS.has(bare.toUpperCase())) return token.toUpperCase();

  const lower = token.toLowerCase();
  if (index > 0 && MINOR.has(lower.replace(/[^\p{L}]/gu, ''))) return lower;

  // Capitalise after the first letter, so "(john's" and "o'brien" both work.
  return lower.replace(/\p{L}[\p{L}\p{M}']*/gu, (word, offset: number) => {
    // Do not re-capitalise the second half of a contraction.
    if (offset > 0 && lower[offset - 1] === "'") return word;
    return word.charAt(0).toUpperCase() + word.slice(1);
  });
}

function toTitleCase(text: string): string {
  return text
    .split(/(\s+)/)
    .map((part, i) => (/\s/.test(part) ? part : recaseToken(part, i / 2)))
    .join('');
}

/**
 * Soften shouted titles.
 *
 * Two rules, in order: a leading run of two or more all-caps words is recased,
 * and a title that is 60% or more uppercase is recased entirely. The feed has
 * plenty of both, and "BLACKBIRD FORUM: Reshaping Healthcare" reads as an
 * error rather than as emphasis.
 */
export function cleanTitle(title: string): string {
  const trimmed = title.trim();
  if (trimmed === '') return trimmed;

  const letters = [...trimmed].filter((c) => LETTER.test(c));
  if (letters.length === 0) return trimmed;

  const upperShare = letters.filter((c) => UPPER.test(c)).length / letters.length;
  if (upperShare >= 0.6) return toTitleCase(trimmed);

  const tokens = trimmed.split(/(\s+)/);
  const words: Array<{ index: number; value: string }> = [];
  tokens.forEach((t, i) => {
    if (!/\s/.test(t) && t !== '') words.push({ index: i, value: t });
  });

  let run = 0;
  while (run < words.length && isAllCapsWord(words[run]!.value)) run++;
  if (run < 2) return trimmed;

  const next = [...tokens];
  for (let w = 0; w < run; w++) {
    const slot = words[w]!;
    next[slot.index] = recaseToken(slot.value, w);
  }
  return next.join('');
}

const LUMA_USER = /^luma user\b/i;

/**
 * Some sources emit an internal handle where the organizer should be, such as
 * "Luma User cTlmPNsi6jHYweP". Showing that is worse than admitting we do not
 * know who is running it.
 */
export function isAutoGeneratedOrganizer(name: string): boolean {
  const trimmed = name.trim();
  if (trimmed === '') return true;
  if (LUMA_USER.test(trimmed)) return true;
  // A single opaque token: long, no spaces, and mixing letters with digits.
  if (!/\s/.test(trimmed) && trimmed.length >= 10 && /\p{L}/u.test(trimmed) && /\d/.test(trimmed)) {
    return true;
  }
  return false;
}

export const ANONYMOUS_ORGANIZER = 'Independent organizer';

export function cleanOrganizer(name: string): string {
  return isAutoGeneratedOrganizer(name) ? ANONYMOUS_ORGANIZER : name.trim();
}

const ONLINE_HINT = /\b(online|virtual|zoom)\b/i;

/** True when the location names a screen rather than a place. */
export function looksOnline(
  venue: string | null,
  address: string | null,
  locality: string | null,
): boolean {
  return [venue, address, locality].some((v) => v !== null && ONLINE_HINT.test(v));
}

/**
 * Two initials for the avatar. Falls back to the venue when the organizer is
 * anonymous, so the circle still says something true.
 */
export function initialsFor(primary: string, fallback: string | null): string {
  const source =
    isAutoGeneratedOrganizer(primary) && fallback && fallback.trim() !== '' ? fallback : primary;
  const words = source
    .replace(/[^\p{L}\p{N}\s]/gu, ' ')
    .split(/\s+/)
    .filter((w) => w !== '' && !MINOR.has(w.toLowerCase()));
  if (words.length === 0) return '?';
  if (words.length === 1) return words[0]!.slice(0, 2).toUpperCase();
  return (words[0]!.charAt(0) + words[1]!.charAt(0)).toUpperCase();
}

/** Field labels the scrapers pick up when a page has no real title. */
const LABEL_TITLE =
  /^(start|end)?\s*date(\s+and\s+time)?$|^time\s*zone\s*notice:?$|^(next|previous|prev|more|details|read\s+more|rsvp|register|untitled\s+event|event|all\s+day)$/i;

/**
 * A scraper that hit an empty result page and stored the page's apology as an
 * event. One row in the feed does this, and it is the worst single string the
 * grid could show: an event whose title says there are no events.
 */
const SCRAPED_ERROR = /there were no .{0,40}found|no results? (were )?found|please search again/i;

/** A bare ISO stamp, or a bare clock time, standing in for a title. */
const STAMP_TITLE = /^\d{4}-\d{2}-\d{2}([T\s]\d{2}:\d{2}(:\d{2})?)?$/;
const CLOCK_TITLE = /^\d{1,2}:\d{2}\s*([ap]\.?m\.?)?$/i;

/** Nothing but a street address, with no event name attached. */
const ADDRESS_TITLE =
  /^\d+[a-z]?\s+([\w.'-]+\s+){0,4}(st|street|ave|avenue|rd|road|blvd|boulevard|ln|lane|dr|drive|way|pl|place|ct|court|pkwy|parkway|hwy|highway|sq|square|ter|terrace)\.?$/i;

/**
 * Does this title tell a reader nothing about the event?
 *
 * 15 of the feed's 1,695 rows carry a form-field label, a raw timestamp or a
 * bare street address where the title should be. That is under 1%, but the
 * month grid previews only two events per day and picked them in feed order,
 * so those 15 rows were filling a visibly large share of the grid.
 *
 * This only ever *demotes* a title in a preview. The event keeps its place in
 * the list, the day count still includes it, and the raw value is untouched —
 * dropping a real event to tidy a cell would be the worse trade.
 */
export function isPlaceholderTitle(title: string): boolean {
  const t = title.trim();
  if (t === '') return true;
  return (
    LABEL_TITLE.test(t) ||
    STAMP_TITLE.test(t) ||
    CLOCK_TITLE.test(t) ||
    ADDRESS_TITLE.test(t) ||
    SCRAPED_ERROR.test(t)
  );
}
