import { describe, expect, it } from 'vitest';
import {
  ANONYMOUS_ORGANIZER,
  cleanOrganizer,
  cleanTitle,
  isPlaceholderTitle,
  initialsFor,
  isAutoGeneratedOrganizer,
  looksOnline,
} from './display';

describe('cleanTitle', () => {
  it('recases a leading run of shouted words', () => {
    expect(cleanTitle('BLACKBIRD FORUM: Reshaping Healthcare with AI')).toBe(
      'Blackbird Forum: Reshaping Healthcare with AI',
    );
  });

  it('leaves a single capitalised word alone', () => {
    // One all-caps word is emphasis, not a formatting accident.
    expect(cleanTitle('FREE yoga in the park')).toBe('FREE yoga in the park');
  });

  it('recases a title that is mostly uppercase', () => {
    expect(cleanTitle('COMMUNITY POTLUCK AND GAME NIGHT')).toBe('Community Potluck and Game Night');
  });

  it('keeps acronyms', () => {
    expect(cleanTitle('AI AND UX WORKSHOP AT UMBC')).toBe('AI and UX Workshop at UMBC');
    expect(cleanTitle('NASA STEM DAY')).toBe('NASA STEM Day');
  });

  it('keeps any token containing a digit', () => {
    expect(cleanTitle('BALTIMORE MARATHON 5K 2026')).toBe('Baltimore Marathon 5K 2026');
    expect(cleanTitle('3D PRINTING BASICS')).toBe('3D Printing Basics');
  });

  it('never lowercases a leading minor word', () => {
    expect(cleanTitle('THE ART OF THE DEAL')).toBe('The Art of the Deal');
  });

  it('handles apostrophes without capitalising mid-word', () => {
    expect(cleanTitle("RED EMMA'S BOOK CLUB")).toBe("Red Emma's Book Club");
  });

  it('leaves ordinary titles untouched', () => {
    const ok = 'Bmore on Rails, September meetup';
    expect(cleanTitle(ok)).toBe(ok);
  });

  it('survives punctuation-only and empty input', () => {
    expect(cleanTitle('   ')).toBe('');
    expect(cleanTitle('!!!')).toBe('!!!');
  });
});

describe('organizer names', () => {
  it('spots the Luma handles the feed actually carries', () => {
    expect(isAutoGeneratedOrganizer('Luma User cTlmPNsi6jHYweP')).toBe(true);
    expect(cleanOrganizer('Luma User k0oO7FswDxbAWh0')).toBe(ANONYMOUS_ORGANIZER);
  });

  it('spots a bare opaque token', () => {
    expect(isAutoGeneratedOrganizer('usr7fSwDxbAW0')).toBe(true);
  });

  it('keeps real names, including short ones and ones with digits', () => {
    expect(cleanOrganizer('Red Emma’s')).toBe('Red Emma’s');
    expect(cleanOrganizer('Unallocated Space')).toBe('Unallocated Space');
    expect(cleanOrganizer('Towson Lodge #79')).toBe('Towson Lodge #79');
    expect(isAutoGeneratedOrganizer('Baltimore Orioles')).toBe(false);
  });
});

describe('online detection', () => {
  it('matches the words the feed uses', () => {
    expect(looksOnline('Online event', null, null)).toBe(true);
    expect(looksOnline(null, 'Virtual, MD', null)).toBe(true);
    expect(looksOnline('Zoom', null, null)).toBe(true);
  });

  it('does not match a place that merely contains the letters', () => {
    // "Zoomers Cafe" is a venue, not a video call.
    expect(looksOnline('Zoomers Cafe', null, null)).toBe(false);
    expect(looksOnline('Online Avenue Studios', null, null)).toBe(true);
  });

  it('is false when there is no location at all', () => {
    expect(looksOnline(null, null, null)).toBe(false);
  });
});

describe('initials', () => {
  it('takes the first letters of the first two words', () => {
    expect(initialsFor('Baltimore Orioles', null)).toBe('BO');
    expect(initialsFor('Red Emma’s Bookstore', null)).toBe('RE');
  });

  it('doubles up on a single word', () => {
    expect(initialsFor('Betamore', null)).toBe('BE');
  });

  it('falls back to the venue when the organizer is a handle', () => {
    expect(initialsFor('Luma User cTlmPNsi6jHYweP', 'Spark Baltimore')).toBe('SB');
  });

  it('skips minor words', () => {
    expect(initialsFor('The Charmers Club', null)).toBe('CC');
  });

  it('never returns an empty string', () => {
    expect(initialsFor('', null)).toBe('?');
    expect(initialsFor('!!!', null)).toBe('?');
  });
});

describe('isPlaceholderTitle', () => {
  it('catches the shapes the feed actually ships', () => {
    for (const t of [
      '2026-09-30T18:30:00',
      '2026-10-06',
      'Start Date and Time',
      'Date and Time',
      'Time Zone Notice:',
      'Next',
      'NEXT',
      '212 S Bond Street',
      '212 S Bond St',
      '7:30 PM',
      '   ',
    ]) {
      expect(isPlaceholderTitle(t), t).toBe(true);
    }
  });

  it('leaves real titles alone, including ones that open with a number', () => {
    for (const t of [
      'Camera-Ready Deadline',
      '2026 World Series presented by Capital One',
      '1919 Market Street Opening Night',
      '3D Printing Basics',
      'Baltimore Ravens vs Atlanta Falcons',
      'Next Steps in Machine Learning',
      '5K for Charity',
    ]) {
      expect(isPlaceholderTitle(t), t).toBe(false);
    }
  });
});
